@startuml name
rectangle "origin" {
    node main as github_main
}

rectangle "local" {
    rectangle "remote cache" {
        node "origin/main" as gh_main
    }
    node main
}

github_main -- gh_main
gh_main -- main


@enduml