@startuml name
rectangle origin {
    node main as github_main
}

rectangle "local repository" {
    rectangle "remote cache" {
        node "origin/main" as gh_main
    }
    node main
}

rectangle "local repository2" {
    rectangle "remote cache 2" {
        node "origin/main" as gh_main2
    }
    node "main" as main2
}

github_main --gh_main
gh_main -- main

github_main --gh_main2
gh_main2 -- main2


@enduml