@startuml name
rectangle github {
    node main as github_main
    node dev as github_dev
}

rectangle "local repository" {
    node "github/main" as gh_main
    node "github/dev" as gh_dev
    node main
    node dev
}

github_main -- gh_main
gh_main -- main

github_dev -- gh_dev
gh_dev -- dev


@enduml